name: EAuth
version: '0.6'
main: dev.elysium.eAuth.EAuth
api-version: '1.21'
depend: [EAPI]

commands:
  login:
    description: Авторизация
  l:
    description: Авторизация
  register:
    description: Регистрация
  reg:
    description: Регистрация